version: "3.4"

services:
  ## MYSQL SERVER
  mysql-server:
    image: mysql:5.7
    ports:
    - 3310:3306 # extenal:internal
    env_file:
    - ./env/mysql-server-conf.env

  ## NODE JS SERVER
  node-server:
    build:
      context: ./ # Dockerfile location
    image: node-ts-intro:latest #Name given to the image:tag
    depends_on:
    - mysql-server
    ports:
    - 80:3000 # extenal:internal

    ## Map local directoery to image app dir
    volumes:
    - ./:/app
    ## Override start commandin Dockerfile
    command: yarn run dev

networks:
  testnetwork


